version: '3.8'

services:
  wordpress:
    build:
      context: .
      dockerfile: ./wordpress/Dockerfile
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress/app:/var/www/html/app
    depends_on:
      - db
  db:
    ports:
      - "3307:3306"
    image: mariadb:10.6.4-focal
    volumes:
      - ./db:/var/lib/mysql
      - ./config/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy-wp
    ports:
      - "443:443"
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - ./wordpress/app:/var/www/html/app
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/certs/:/etc/nginx/certs/:ro
    depends_on:
      - wordpress

volumes:
  db_data: